# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johan Hammar
email: johan.hammar@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.johanhammar.se"
enforce_ssl: "www.johanhammar.se"
twitter_username: johanh
mastodon_username: "@johanhammar"
github_username:  johanhammar
linkedin_username: johanhammar
goodreads_username: johanhammar
spotify_username: johanhammar
dev_username: johanhammar

author:
    name: 'Johan Hammar'
    country: Sweden
    username:
        twitter: johanh
        github: johanhammar

# Build settings
markdown: kramdown

plugins:
  - jemoji
