# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johan Hammar
email: johan.hammar@gmail.com
description: Development notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.johanhammar.se" # the base hostname & protocol for your site
twitter_username: johanh
github_username:  johanhammar

# Build settings
markdown: kramdown
